version: "3.7"

services:
  server:
    image: nginx:stable-alpine
    container_name: server
    ports:
      - 8000:80
    volumes:
      - ../back-king-tide:/var/www/html/back-king-tide
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ktide-ntw
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ../back-king-tide:/var/www/html/back-king-tide
    ports:
      - 9000:80
    networks:
      - ktide-ntw

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_DATABASE: king_tide
      MYSQL_USER: king_tide_user
      MYSQL_PASSWORD: ktide_pass
      MYSQL_ROOT_PASSWORD: ktide_pass
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - ktide-ntw

  front:
    container_name: front
    image: node:16-alpine
    volumes:
      - "../front-king-tide:/app"
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    networks:
      - ktide-ntw
networks:
  ktide-ntw:
